[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sender = "0x0f14341A7f464320319025540E8Fe48Ad0fe5aec"
force = true
optimizer = true
auto_detect_remappings = false
optimizer_runs = 999999
evm_version = "london"
bytecode_hash = "ipfs"
extra_output_files = ["metadata"]

[rpc_endpoints]
koi = "https://koi-rpc.darwinia.network"
crab = "https://crab-rpc.darwinia.network"

[etherscan]
koi = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://koi-scan.darwinia.network/api" }
crab = { key = "${ETHERSCAN_DARWINIA_KEY}", url = "https://crab-scan.darwinia.network/api" }
